name: release-1.4

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - run: export GO111MODULE=auto

    - name: Test build
      run: cd orderer; go build
